[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.crm.obj.schemas"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["schema", "hubspot", "object"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.object.schemas"

[build-options]
observabilityIncluded = true
